name = Front Page
description = Front page layout for MasterSalesVideos
template = frontpage-layout

; Regions
regions[branding]       = Branding

regions[thumbnail_1]    = Thumbnail 1
regions[thumbnail_2]    = Thumbnail 2
regions[thumbnail_3]    = Thumbnail 3
regions[thumbnail_4]    = Thumbnail 4

regions[video]          = Video
regions[request]        = Request

regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/frontpage/frontpage.layout.css
stylesheets[all][] = css/layouts/frontpage/frontpage.layout.no-query.css
